######################## ALL FIELDS ARE REQUIRED UNLESS OTHERWISE NOTED #########################

######################################### TASK METADATA #########################################
############################ Will be displayed in the desktop node ##############################

## Task Name ##
# Maximum 24 characters.
task_name: "Prometheus Builder Beta"

## Task Author ##
author: "Koii"

# Task Description Markdown ##
# If you specify a markdown file, the description field will be ignored.
# Markdown is recommended for better formatting.
markdownDescriptionPath: "../../README.md"

## Task Description ##
# Ignored if you specify a markdown file.
description: "Task description."

## Repository URL ##
# Must be public for whitelisted tasks.
repositoryUrl: "https://github.com/koii-network/builder-247"

## Image URL ##
# 230x86 pixels.
imageUrl: "https://raw.githubusercontent.com/koii-network/builder-247/refs/heads/main/prometheus.png"

## Info URL ##
infoUrl: "https://www.koii.network/blog/Earn-Crypto-With-AI-Agent"

####################################### TASK CONFIGURATION ######################################

## Task Executable Network ##
# IPFS or DEVELOPMENT
# Keep this as IPFS unless you know you need to change it.
task_executable_network: "IPFS"

## Task Audit Program ##
# Task Executable Network IPFS: Path to your executable.
# Task Executable Network DEVELOPMENT: The value should be 'main'.
# Keep this as-is unless you know you need to change it.
task_audit_program: "dist/main.js"

## Round Time ##
# Duration of task, measured in slots (with each slot approximately equal to 408ms). Should be at least 800 slots.
# See https://www.koii.network/docs/concepts/what-are-tasks/what-are-tasks/gradual-consensus for more information on how round time, audit window, and submission window work.
round_time: 9000

## Audit Window ##
# The audit window should be at least 1/3 of the round time.
audit_window: 3000

## Submission Window ##
# The submission window should be at least 1/3 of the round time.
submission_window: 3000

## Minimum Stake Amount ##
# The minimum amount of KOII or KPL that a user must stake in order to participate in the task.
minimum_stake_amount: 1.9

## Task Bounty Type ##
# KOII or KPL
task_type: "KOII"

## Token Mint Address (ONLY for KPL tasks) ##
# The Fire Token address is provided as an example.
token_type: "4qayyw53kWz6GzypcejjT1cvwMXS1qYLSMQRE8se3gTv"

## Total Bounty Amount ##
# The total bounty amount that will be available for distribution over all rounds.
# Does nothing when updating a task.
total_bounty_amount: 30000

## Bounty Amount per Round ##
# The maximum amount that can be distributed per round.
# If the actual distribution per round exceeds this amount, the distribution list will fail.
bounty_amount_per_round: 625

## Allowed Failed Distributions ##
# Number of retries allowed for the distribution list if it is fails audit.
# If all retries fail, the task will not distribute anything for the round.
# This is also the number of rounds of submissions it will keep.
allowed_failed_distributions: 3

## Space ##
# Expected Task Data Size in MBs for the account size.
# Minimums: 2 for whitelisted tasks, 1 for production, 0.1 for testing.
# See https://www.koii.network/docs/develop/command-line-tool/create-task-cli/create-task#space for calculation details.
space: 2

## Requirement Tags (Optional) ##
# To add more global variables and task variables, please refer to the type, value, description format shown below.
# The ORCA_TASK addon is REQUIRED
requirementsTags:
  - type: ADDON
    value: "ORCA_TASK"
  - type: CPU
    value: "4-core"
  - type: RAM
    value: "5 GB"
  - type: STORAGE
    value: "5 GB"
  - type: TASK_VARIABLE
    value: "ANTHROPIC_API_KEY"
    description: "Your Anthropic API key. You can get one here: https://console.anthropic.com/settings/keys"
  - type: TASK_VARIABLE
    value: "GITHUB_USERNAME"
    description: "Your GitHub username. You can sign up for an account here: https://github.com/join"
  - type: TASK_VARIABLE
    value: "GITHUB_TOKEN"
    description: "Your GitHub Personal Access Token. You can create one here: https://github.com/settings/tokens"

## Tags ##
# See https://www.koii.network/docs/develop/command-line-tool/create-task-cli/create-task#tags for available tag options.
tags: ["AI"]

# Environment ##
# TEST or PRODUCTION
# Production mode will expose your task to all the task runners, even if not whitelisted.
environment: "PRODUCTION"

#################################### FOR UPDATING TASKS ONLY ####################################

## Old Task ID ##
task_id: "hF7G6BR59L6F3dDfJFrL3N8AtvKpS4GJjrAJL5cQA5V"

## Migration Description ##
migrationDescription: "Fix audit bug"
